import { useEffect, useMemo, useState } from 'react'
import { Activity, ArrowRight, BusFront, Check, ChevronDown, CircleAlert, LayoutDashboard, LogOut, Menu, Plus, RefreshCw, Settings2, ShieldCheck, TrainFront, UserRound, Users, X } from 'lucide-react'
import { api } from './api'

const MENU = [
  { key: 'dashboard', label: 'Dashboard', icon: LayoutDashboard, roles: ['Admin', 'Operator', 'Manager'] },
  { key: 'trains', label: 'Trains', icon: TrainFront, roles: ['Admin', 'Operator', 'Manager'] },
  { key: 'carriages', label: 'Carriages', icon: BusFront, roles: ['Admin', 'Operator', 'Manager'] },
  { key: 'seats', label: 'Seats', icon: Settings2, roles: ['Admin', 'Operator', 'Manager'] },
  { key: 'manifest', label: 'Manifest', icon: Activity, roles: ['Admin', 'Operator'] },
  { key: 'employees', label: 'Employees', icon: Users, roles: ['Admin'] },
  { key: 'bookings', label: 'Bookings', icon: Check, roles: ['Admin', 'Operator', 'Manager'] },
  { key: 'reports', label: 'Reports', icon: Activity, roles: ['Admin', 'Operator', 'Manager'] },
  { key: 'logs', label: 'System Logs', icon: ShieldCheck, roles: ['Admin'] },
]

function Login({ onLogin }) {
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [error, setError] = useState('')
  const [loading, setLoading] = useState(false)
  async function submit(event) {
    event.preventDefault(); setError(''); setLoading(true)
    try { const result = await api.login(email, password); sessionStorage.setItem('whoosh-cms-token', result.access_token); onLogin() } catch (e) { setError(e.message) } finally { setLoading(false) }
  }
  return <main className="login-shell"><div className="login-copy"><div className="brand">Whoosh<span>.</span></div><span className="eyebrow">Back office workspace</span><h1>Manage the journey behind every seat.</h1><p>Secure operations for trains, carriages, and seat configuration.</p></div><form className="login-card" onSubmit={submit}><div className="login-symbol"><ShieldCheck size={24} /></div><span className="eyebrow">CMS sign in</span><h2>Welcome back</h2><p className="muted">Use your authorized Whoosh account to continue.</p><label>Email<input type="email" required value={email} onChange={(e) => setEmail(e.target.value)} placeholder="you@whoosh.id" /></label><label>Password<input type="password" required value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Enter password" /></label>{error && <div className="alert error"><CircleAlert size={16} />{error}</div>}<button className="button primary full" disabled={loading}>{loading ? 'Signing in...' : 'Sign in'} <ArrowRight size={17} /></button><small className="login-note">CMS access is restricted to Admin, Operator, and Manager roles.</small></form></main>
}

function Shell({ user, page, setPage, onLogout, children }) {
  const [open, setOpen] = useState(false)
  const visible = MENU.filter((item) => item.roles.includes(user.role.name))
  return <div className="app-shell"><aside className={`sidebar ${open ? 'open' : ''}`}><div className="sidebar-brand"><div className="brand">Whoosh<span>.</span></div><small>OPERATIONS CMS</small></div><nav>{visible.map((item) => { const Icon = item.icon; return <button key={item.key} className={page === item.key ? 'active' : ''} onClick={() => { setPage(item.key); setOpen(false) }}><Icon size={18} />{item.label}</button> })}<div className="nav-divider" />{MENU.filter((item) => !item.roles.includes(user.role.name)).map((item) => { const Icon = item.icon; return <button key={item.key} className="disabled-nav" title="Not available for this role"><Icon size={18} />{item.label}<span>•</span></button> })}</nav><div className="sidebar-footer"><div className="avatar">{user.name.slice(0, 1)}</div><div><strong>{user.name}</strong><small>{user.role.name}</small></div><button onClick={onLogout} aria-label="Log out"><LogOut size={16} /></button></div></aside><div className="main-shell"><header className="topbar"><button className="menu-toggle" onClick={() => setOpen(!open)}><Menu size={21} /></button><div><span className="breadcrumb">Operations /</span><strong>{MENU.find((item) => item.key === page)?.label || 'Dashboard'}</strong></div><div className="topbar-user"><span className="status-dot" />{user.role.name}<button onClick={onLogout}><LogOut size={16} /></button></div></header><div className="content">{children}</div></div></div>
}

function PageHeader({ eyebrow, title, description, action }) { return <div className="page-header"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{description}</p></div>{action}</div> }
function StatCard({ label, value, icon: Icon, tone }) { return <div className="stat-card"><div className={`stat-icon ${tone}`}><Icon size={20} /></div><div><span>{label}</span><strong>{value}</strong></div></div> }
function StatusBadge({ value }) { return <span className={`status-badge ${value}`}>{value}</span> }
function Empty({ text }) { return <div className="empty"><Activity size={24} /><strong>{text}</strong><span>Data will appear here once it is available from the API.</span></div> }
function ErrorBox({ message }) { return message ? <div className="alert error"><CircleAlert size={16} />{message}</div> : null }

function Dashboard({ refreshKey }) {
  const [data, setData] = useState({ trains: [], carriages: 0, seats: 0 }); const [error, setError] = useState('')
  useEffect(() => { let active = true; Promise.all([api.trains(), api.trains('active')]).then(async ([all, activeTrains]) => { const carriages = (await Promise.all(all.map((train) => api.carriages(train.id)))).flat(); const seats = (await Promise.all(carriages.map((carriage) => api.seats(carriage.id)))).flat(); if (active) setData({ trains: all, activeTrains, carriages, seats }) }).catch((e) => active && setError(e.message)); return () => { active = false } }, [refreshKey])
  return <><PageHeader eyebrow="Control center" title="Good morning, operator." description="A live view of the master data powering employee seat availability." action={<button className="icon-action" onClick={() => location.reload()}><RefreshCw size={16} /> Refresh</button>} /><ErrorBox message={error} /><div className="stats-grid"><StatCard label="Total trains" value={data.trains.length} icon={TrainFront} tone="red" /><StatCard label="Active trains" value={data.activeTrains?.length || 0} icon={Activity} tone="green" /><StatCard label="Total carriages" value={data.carriages.length} icon={BusFront} tone="blue" /><StatCard label="Configured seats" value={data.seats.length} icon={Settings2} tone="gold" /></div><section className="panel"><div className="panel-head"><div><span className="eyebrow">Live inventory</span><h2>Recent trains</h2></div><span className="muted">{data.trains.length} records</span></div>{data.trains.length ? <div className="table-wrap"><table><thead><tr><th>Train</th><th>Route</th><th>Travel date</th><th>Class</th><th>Status</th></tr></thead><tbody>{data.trains.slice(0, 8).map((train) => <tr key={train.id}><td><strong>{train.train_number}</strong></td><td>{train.route_from} <ArrowRight size={13} /> {train.route_to}</td><td>{train.travel_date}</td><td>{train.class_type}</td><td><StatusBadge value={train.status} /></td></tr>)}</tbody></table></div> : <Empty text="No trains configured" />}</section></>
}

const blankTrain = { train_number: '', route_from: '', route_to: '', travel_date: '', class_type: 'Premium Economy', status: 'active' }
function TrainForm({ initial, onClose, onSaved }) { const [form, setForm] = useState(initial || blankTrain); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); const edit = Boolean(initial?.id); const change = (key, value) => setForm((x) => ({ ...x, [key]: value })); async function submit(e) { e.preventDefault(); setSaving(true); setError(''); try { edit ? await api.updateTrain(initial.id, form) : await api.createTrain(form); onSaved() } catch (err) { setError(err.message) } finally { setSaving(false) } } return <div className="modal-backdrop"><form className="modal-card" onSubmit={submit}><button type="button" className="modal-close" onClick={onClose}><X size={18} /></button><span className="eyebrow">{edit ? 'Edit train' : 'New train'}</span><h2>{edit ? 'Update train details' : 'Create a train'}</h2><div className="form-grid"><label>Train number<input required value={form.train_number} onChange={(e) => change('train_number', e.target.value)} /></label><label>Travel date<input type="date" required value={form.travel_date} onChange={(e) => change('travel_date', e.target.value)} /></label><label>Route from<input required value={form.route_from} onChange={(e) => change('route_from', e.target.value)} /></label><label>Route to<input required value={form.route_to} onChange={(e) => change('route_to', e.target.value)} /></label><label>Class type<input required value={form.class_type} onChange={(e) => change('class_type', e.target.value)} /></label><label>Status<select value={form.status} onChange={(e) => change('status', e.target.value)}><option value="active">Active</option><option value="inactive">Inactive</option><option value="archived">Archived</option></select></label></div><ErrorBox message={error} /><div className="modal-actions"><button type="button" className="button ghost" onClick={onClose}>Cancel</button><button className="button primary" disabled={saving}>{saving ? 'Saving...' : edit ? 'Save changes' : 'Create train'}</button></div></form></div> }

function Trains({ canManage }) { const [trains, setTrains] = useState([]); const [filter, setFilter] = useState(''); const [search, setSearch] = useState(''); const [error, setError] = useState(''); const [modal, setModal] = useState(null); const [notice, setNotice] = useState(''); async function load() { try { setError(''); setTrains(await api.trains(filter)) } catch (e) { setError(e.message) } } useEffect(() => { load() }, [filter]); const shown = useMemo(() => trains.filter((x) => `${x.train_number} ${x.route_from} ${x.route_to}`.toLowerCase().includes(search.toLowerCase())), [trains, search]); async function toggle(train) { const next = train.status === 'active' ? 'inactive' : 'active'; if (!confirm(`${next === 'inactive' ? 'Deactivate' : 'Activate'} ${train.train_number}?`)) return; try { await api.updateTrainStatus(train.id, next); setNotice(`${train.train_number} is now ${next}.`); load() } catch (e) { setError(e.message) } } return <><PageHeader eyebrow="Master data" title="Trains" description="Create and maintain the trips available to the Whoosh network." action={canManage && <button className="button primary" onClick={() => setModal('new')}><Plus size={17} /> New train</button>} /><div className="toolbar"><div className="search"><Activity size={16} /><input placeholder="Search train or route" value={search} onChange={(e) => setSearch(e.target.value)} /></div><select value={filter} onChange={(e) => setFilter(e.target.value)}><option value="">All statuses</option><option value="active">Active</option><option value="inactive">Inactive</option><option value="archived">Archived</option></select></div>{notice && <div className="alert success"><Check size={16} />{notice}</div>}<ErrorBox message={error} /><section className="panel"><div className="table-wrap"><table><thead><tr><th>Train</th><th>Route</th><th>Travel date</th><th>Class</th><th>Status</th><th /></tr></thead><tbody>{shown.map((train) => <tr key={train.id}><td><strong>{train.train_number}</strong></td><td>{train.route_from} <ArrowRight size={13} /> {train.route_to}</td><td>{train.travel_date}</td><td>{train.class_type}</td><td><StatusBadge value={train.status} /></td><td className="row-actions">{canManage && <><button onClick={() => setModal(train)}>Edit</button><button onClick={() => toggle(train)}>{train.status === 'active' ? 'Deactivate' : 'Activate'}</button></>}</td></tr>)}</tbody></table>{!shown.length && <Empty text="No trains found" />}</div></section>{modal && <TrainForm initial={modal === 'new' ? null : modal} onClose={() => setModal(null)} onSaved={() => { setModal(null); setNotice('Train saved successfully.'); load() }} />}</> }

function Carriages({ canManage }) { const [trains, setTrains] = useState([]); const [trainId, setTrainId] = useState(''); const [items, setItems] = useState([]); const [modal, setModal] = useState(null); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); useEffect(() => { api.trains().then(setTrains).catch((e) => setError(e.message)) }, []); useEffect(() => { if (trainId) api.carriages(trainId).then(setItems).catch((e) => setError(e.message)); else setItems([]) }, [trainId]); async function save(form) { try { if (modal.id) await api.updateCarriage(modal.id, form); else await api.createCarriage(trainId, form); setModal(null); setNotice('Carriage saved successfully.'); setItems(await api.carriages(trainId)) } catch (e) { setError(e.message) } } async function toggle(item) { try { await api.updateCarriageStatus(item.id, item.status === 'active' ? 'inactive' : 'active'); setItems(await api.carriages(trainId)) } catch (e) { setError(e.message) } } return <><PageHeader eyebrow="Master data" title="Carriages" description="Configure carriage rows and flexible seat layouts per train." action={canManage && trainId && <button className="button primary" onClick={() => setModal({})}><Plus size={17} /> Add carriage</button>} /><div className="toolbar"><select value={trainId} onChange={(e) => setTrainId(e.target.value)}><option value="">Select a train</option>{trains.map((train) => <option key={train.id} value={train.id}>{train.train_number} · {train.route_from} → {train.route_to}</option>)}</select></div><ErrorBox message={error} />{notice && <div className="alert success"><Check size={16} />{notice}</div>}{!trainId ? <Empty text="Select a train to view carriages" /> : <section className="card-grid">{items.map((item) => <article className="data-card" key={item.id}><div className="data-card-top"><span className="carriage-number">{item.carriage_number}</span><StatusBadge value={item.status} /></div><h2>{item.class_type}</h2><p>{item.total_rows} rows · {item.seat_config.join(' · ')}</p><div className="data-card-actions">{canManage && <><button onClick={() => setModal(item)}>Edit</button><button onClick={() => toggle(item)}>{item.status === 'active' ? 'Deactivate' : 'Activate'}</button></>}</div></article>)}{!items.length && <Empty text="No carriages configured" />}</section>}{modal && <CarriageForm initial={modal.id ? modal : null} onClose={() => setModal(null)} onSave={save} />}</> }

function CarriageForm({ initial, onClose, onSave }) { const [form, setForm] = useState({ carriage_number: initial?.carriage_number || '', class_type: initial?.class_type || 'Premium Economy', total_rows: initial?.total_rows || 1, seat_config: initial?.seat_config?.join(',') || 'A,B,C,D,F', status: initial?.status || 'active' }); const change = (key, value) => setForm((x) => ({ ...x, [key]: value })); return <div className="modal-backdrop"><form className="modal-card" onSubmit={(e) => { e.preventDefault(); onSave({ ...form, total_rows: Number(form.total_rows), seat_config: form.seat_config.split(',').map((x) => x.trim()).filter(Boolean) }) }}><button type="button" className="modal-close" onClick={onClose}><X size={18} /></button><span className="eyebrow">{initial ? 'Edit carriage' : 'New carriage'}</span><h2>Seat configuration</h2><div className="form-grid"><label>Carriage number<input required value={form.carriage_number} onChange={(e) => change('carriage_number', e.target.value)} /></label><label>Total rows<input type="number" min="1" required value={form.total_rows} onChange={(e) => change('total_rows', e.target.value)} /></label><label>Class type<input required value={form.class_type} onChange={(e) => change('class_type', e.target.value)} /></label><label>Status<select value={form.status} onChange={(e) => change('status', e.target.value)}><option value="active">Active</option><option value="inactive">Inactive</option><option value="archived">Archived</option></select></label><label className="wide">Seat configuration <small>Comma-separated values, e.g. A,B,C,D,F</small><input required value={form.seat_config} onChange={(e) => change('seat_config', e.target.value)} /></label></div><div className="modal-actions"><button type="button" className="button ghost" onClick={onClose}>Cancel</button><button className="button primary">Save carriage</button></div></form></div> }

function Seats({ canManage }) { const [trains, setTrains] = useState([]); const [carriages, setCarriages] = useState([]); const [trainId, setTrainId] = useState(''); const [carriageId, setCarriageId] = useState(''); const [seats, setSeats] = useState([]); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); useEffect(() => { api.trains().then(setTrains).catch((e) => setError(e.message)) }, []); useEffect(() => { if (trainId) api.carriages(trainId).then(setCarriages).catch((e) => setError(e.message)); else setCarriages([]); setCarriageId(''); setSeats([]) }, [trainId]); useEffect(() => { if (carriageId) api.seats(carriageId).then(setSeats).catch((e) => setError(e.message)); else setSeats([]) }, [carriageId]); async function generate() { try { const result = await api.generateSeats(carriageId); setSeats(result.seats); setNotice(`${result.generated_count} seats generated.`) } catch (e) { setError(e.message) } } const rows = Object.values(seats.reduce((group, seat) => { (group[seat.row_number] ||= []).push(seat); return group }, {})); return <><PageHeader eyebrow="Master data" title="Seats" description="Inspect generated seats and keep configuration aligned with each carriage." action={canManage && carriageId && !seats.length && <button className="button primary" onClick={generate}><Settings2 size={17} /> Generate seats</button>} /><div className="toolbar"><select value={trainId} onChange={(e) => setTrainId(e.target.value)}><option value="">Select a train</option>{trains.map((train) => <option key={train.id} value={train.id}>{train.train_number}</option>)}</select><select value={carriageId} onChange={(e) => setCarriageId(e.target.value)} disabled={!trainId}><option value="">Select a carriage</option>{carriages.map((item) => <option key={item.id} value={item.id}>{item.carriage_number} · {item.total_rows} rows</option>)}</select></div><ErrorBox message={error} />{notice && <div className="alert success"><Check size={16} />{notice}</div>}{carriageId && !seats.length && <Empty text="No generated seats yet" />}{seats.length > 0 && <section className="seat-admin-panel"><div className="seat-admin-head"><div><span className="eyebrow">Seat inventory</span><h2>{seats.length} configured seats</h2></div><span className="muted">Read-only view</span></div><div className="admin-seat-map">{rows.map((row) => <div className="admin-seat-row" key={row[0].row_number}><span>{row[0].row_number}</span>{row.map((seat) => <div className={`admin-seat ${seat.status}`} key={seat.id}><strong>{seat.seat_code}</strong><small>{seat.status}</small></div>)}</div>)}</div></section>}</> }

function ComingSoon({ name }) { return <><PageHeader eyebrow="Planned module" title={name} description="This module is reserved for a later phase and is not connected yet." /><div className="coming"><div><Settings2 size={30} /></div><h2>Coming soon</h2><p>No fake functionality here. The backend workflow for this module has not been implemented.</p></div></> }

export default function App() { const [user, setUser] = useState(null); const [page, setPage] = useState(location.hash.slice(1) || 'dashboard'); const [refreshKey, setRefreshKey] = useState(0); useEffect(() => { const token = sessionStorage.getItem('whoosh-cms-token'); if (token) api.me().then(setUser).catch(() => sessionStorage.removeItem('whoosh-cms-token')); const logout = () => setUser(null); window.addEventListener('cms:logout', logout); return () => window.removeEventListener('cms:logout', logout) }, []); function navigate(next) { setPage(next); location.hash = next } function logout() { sessionStorage.removeItem('whoosh-cms-token'); setUser(null) } if (!user) return <Login onLogin={() => api.me().then((next) => { if (!['Admin', 'Operator', 'Manager'].includes(next.role.name)) throw new Error('This account does not have CMS access.'); setUser(next) }).catch(() => { sessionStorage.removeItem('whoosh-cms-token') })} />; const canManage = ['Admin', 'Operator'].includes(user.role.name); const content = page === 'dashboard' ? <Dashboard refreshKey={refreshKey} /> : page === 'trains' ? <Trains canManage={canManage} /> : page === 'carriages' ? <Carriages canManage={canManage} /> : page === 'seats' ? <Seats canManage={canManage} /> : <ComingSoon name={MENU.find((item) => item.key === page)?.label || 'Module'} />; return <Shell user={user} page={page} setPage={navigate} onLogout={logout}>{content}</Shell> }
